flake: mkOutputs: conditionally require asciidoctor-bibtext plugin
Require the bibtex-file plugin only when its required bibtex-file
attribute is defined to prevent the following error:

    Error: bibtex-file is not set and automatic search failed

Fixes: a45884d5b8b0 ("flake: mkOutputs: support asciidoctor-bibtext plugin")